### ISSUE TITLE
Meeting Notes 25/01 

### ISSUE THREAD

**Issue by jean-imperial** [ImperialCollegeLondon/MAG-Data-Visualization-Toolbox#16]
## Agenda
- How to implement CDF reader - jean needs access to IMAP data
- Could sunpy be used to help with this? Demo archive interaction/plotting - could this be used to as a CDF library to save time?
-  Code from Maxine for CDF generation
- Autoflow improvement SO - can we start by replacing CDF readers with code generated for this repo
-  Code from Maxine for CDF generation
## Notes

**Comment by mfacchinelli** [comment]
Moved notes/agenda to OneNote.
